In [44]:
import pandas as pd
from datetime import datetime

In [2]:
df = pd.read_csv("movies.csv")
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,PK,Bollywood,2014,8.1,UTV Motion Pictures,850.0,7563.0,Millions,INR,Hindi
1,Conjuring 2,Hollywood,2016,7.3,Warner Bros. Pictures,40.0,321.0,Millions,USD,English
2,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
3,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
4,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [3]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [4]:
df.shape # ye Instance h

(40, 10)

In [5]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [6]:
# Data Exploration(EDA) - shape, null ,values check ,extract column

In [7]:
# Steps For Analysis- (1 Exploration ),(2 Cleaning), (Transformation),(Insights Decision)

In [8]:
df["studio"].unique()

array(['UTV Motion Pictures', 'Warner Bros. Pictures',
       'Government of West Bengal', 'Marvel Studios', 'MGM Studios',
       'Castle Rock Entertainment', 'Columbia Pictures',
       'Universal Pictures  ', 'Paramount Pictures', 'Liberty Films',
       '20th Century Fox', 'Syncopy', 'Universal Pictures', nan,
       'Yash Raj Films', 'Vinod Chopra Films', 'Dharma Productions',
       'Vinod Chopra Productions', 'Zee Studios', 'Salman Khan Films',
       'Hombale Films', 'Mythri Movie Makers', 'DVV Entertainment',
       'Arka Media Works'], dtype=object)

In [9]:
len(df["studio"].unique())

24

In [10]:
df["studio"].value_counts()

studio
Marvel Studios               8
Vinod Chopra Films           3
Warner Bros. Pictures        2
Dharma Productions           2
Universal Pictures           2
Paramount Pictures           2
Salman Khan Films            2
Columbia Pictures            1
Castle Rock Entertainment    1
MGM Studios                  1
Government of West Bengal    1
UTV Motion Pictures          1
Liberty Films                1
20th Century Fox             1
Universal Pictures           1
Yash Raj Films               1
Syncopy                      1
Vinod Chopra Productions     1
Zee Studios                  1
Hombale Films                1
Mythri Movie Makers          1
DVV Entertainment            1
Arka Media Works             1
Name: count, dtype: int64

In [11]:
df["industry"].value_counts() #nested main suggestion aana band ho jata h

industry
Hollywood    22
Bollywood    18
Name: count, dtype: int64

In [12]:
df.language.value_counts()

language
English    22
Hindi      13
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [13]:
df.currency.value_counts()

currency
USD    22
INR    18
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         40 non-null     object
 1   industry      40 non-null     object
 2   release_year  40 non-null     int64
 3   imdb_rating   39 non-null     float64
 4   studio        37 non-null     object
 5   budget        40 non-null     float64
 6   revenue       40 non-null     float64
 7   unit          40 non-null     object
 8   currency      40 non-null     object
 9   language      40 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.3+ KB

In [15]:
df.describe() # use after when you do unit standardization

       release_year  imdb_rating        budget        revenue
count     40.000000    39.000000     40.000000      40.000000
mean    2006.850000     7.912821   1951.012000    4007.407500
std       17.455511     1.161483  11038.031363   15764.441034
min     1946.000000     1.900000      1.000000       3.100000
25%     2000.750000     7.800000     13.425000     216.900000
50%     2014.000000     8.100000    165.000000     685.900000
75%     2018.000000     8.400000    285.000000    2012.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [16]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
35,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
36,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
37,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
38,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
39,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [17]:
df[["industry","studio","title"]].head()
# agar specific column chahiye to list main values pass kardege(random order main)'"

,industry,studio,title
0,Bollywood,UTV Motion Pictures,PK
1,Hollywood,Warner Bros. Pictures,Conjuring 2
2,Bollywood,Government of West Bengal,Pather Panchali
3,Hollywood,Marvel Studios,Doctor Strange in the Multiverse of Madness
4,Hollywood,Marvel Studios,Thor: The Dark World

In [18]:
# find all marvel movies
df[df.studio == "Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
3,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
4,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
5,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
6,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
20,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
21,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
22,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
23,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [19]:
# Find movies between 2000 to 2010
# in pandas I am not used AND because AND is used to python not in pandas 
# pandas used symbol &

In [32]:
df[((df.release_year >= 2000) & (df.release_year <= 2010) | (df.studio == "marvel Studios"))]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
10,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
11,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
14,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
16,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
25,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
26,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
28,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
29,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [33]:
# add a new column

In [34]:
# function 
def addition(a,b):
    return a+b

In [35]:
addition(3,12)

15

In [40]:
# lamda is anonymous function means jiske pass naam nhi hoga
# used for short ,single - Expression

In [37]:
sum = lambda a,b: a+b

In [38]:
sum (12,34)

46

In [41]:
msg = lambda: "Hello"

In [42]:
msg()

'Hello'

In [46]:

# create a h column and also create this syntax df."age"

In [49]:
df["age"] = df.release_year.apply(lambda release_year_value: datetime.now().year - release_year_value) 
df.head()
# apply is used iteration

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,PK,Bollywood,2014,8.1,UTV Motion Pictures,850.0,7563.0,Millions,INR,Hindi,11
1,Conjuring 2,Hollywood,2016,7.3,Warner Bros. Pictures,40.0,321.0,Millions,USD,English,9
2,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70
3,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3
4,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12